### ISSUE TITLE
powervu 2./3. audio problem hd channels

### ISSUE THREAD

**Issue by jamevu** [oscam-emu/oscam-emu#193]
(dvbapi) PMT6: Trying connect to enigma CA PMT listen socket...
2015/11/26 23:51:37 69761DAD c   (dvbapi) PMT6 CA PMT Server connected on fd 12!
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 ecmpid 0 CAID: 0E00 ECM_PID: 1F76 PROVID: 000000 
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 stream Videostream (MPEG-4)(type: 1b pid: 09c4 length: 0)
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 stream Data-/Audiostream (Subtitles/VBI and AC-3)(type: 06 pid: 09c5 length: 0)
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 stream Data-/Audiostream (Subtitles/VBI and AC-3)(type: 06 pid: 09c9 length: 0)
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 found 1 ECMpids and 3 STREAMpids in caPMT
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 serving srvid 09C8 (0E00@000000:09C8 unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0A22
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 found channel in cache and matching prio -> start descrambling ecmpid 0 
2015/11/26 23:51:55 69761DAD c   (dvbapi) Demuxer 0 trying to descramble PID 0 CAID 0E00 PROVID 000000 ECMPID 1F76 ANY CHID PMTPID 0A22 VPID 09C4
2015/11/26 23:51:55 69761DAD c      (ecm) user1 (0E00@000000/0000/09C8/40:8218E4308B8DE589D7E8900074883A48): found (4 ms) by emulator
2015/11/26 23:51:56 69761DAD c      (ecm) user1 (0E00@000000/0000/09C8/40:3DE81F750465FE41FAA93FD7420952A1): found (7 ms) by emulator
2015/11/26 23:51:56 69761DAD c   (dvbapi) Demuxer 0 stream Videostream (MPEG-4)(type: 1b pid: 09c4 length: 23)
2015/11/26 23:51:56 69761DAD c   (dvbapi) Demuxer 0 stream Data-/Audiostream (Subtitles/VBI and AC-3)(type: 06 pid: 09c5 length: 10)
2015/11/26 23:51:56 69761DAD c   (dvbapi) Demuxer 0 stream Data-/Audiostream (Subtitles/VBI and AC-3)(type: 06 pid: 09c9 length: 10)
2015/11/26 23:51:56 69761DAD c   (dvbapi) Demuxer 0 found 1 ECMpids and 3 STREAMpids in PMT
2015/11/26 23:51:56 69761DAD c   (dvbapi) Demuxer 0 serving srvid 09C8 (0E00@000000:09C8 unknown) on adapter 0000 camask 0001 index 0000 pmtpid 0A22
2015/11/26 23:51:56 69761DAD c      (ecm) user1 (0E00@000000/0000/09C8/40:965513B84ABC1C4E73106DDEDDC8EA65): found (9 ms) by emulator
2015/11/26 23:51:57 69761DAD c      (ecm) user1 (0E00@000000/0000/09C8/40:60D652095FC6B56B82F7DB7511DE6563): found (5 ms) by emulator
2015/11/26 23:51:57 69761DAD c      (ecm) user1 (0E00@000000/0000/09C8/40:6743673867E10C0B5E49234E642F67BA): found (4 ms) by emulator

**Comment by budiarno** [comment]
Use 128 Log mode for digging more on the error messages.

**Comment by jamevu** [comment]
Here it is 128 debug log
[oscam.log.txt](https://github.com/oscam-emu/oscam-emu/files/46164/oscam.log.txt)

**Comment by jamevu** [comment]
![img_20151128_013144](https://cloud.githubusercontent.com/assets/5562122/11449030/21741a36-9570-11e5-8591-dc3b10cfd0af.jpg)

**Comment by budiarno** [comment]
Did I miss "Audio PID" from your Service Info screenshot?

**Comment by jamevu** [comment]
"Ses PID"  is turkish  same as "Audio PID"

**Comment by joeusercz** [comment]
If you are using stream relay, you can use the new patch posted on streamboard.

**Comment by littlesat** [comment]
I found a patch version that solves the audio AC3 issue... (e.g. discovery science HD 1W)
Below the diff..

3c3
< --- CMakeLists.txt	(revision 11212)
---
> --- CMakeLists.txt	(revision 11086)
96,146d95
< Index: Makefile
< ===================================================================
< --- Makefile	(revision 11212)
< +++ Makefile	(working copy)
< @@ -65,6 +65,13 @@
<  
<  LDFLAGS = -Wl,--gc-sections
<  
< +TARGETHELP := $(shell $(CC) --target-help)
< +ifneq (,$(findstring sse2,$(TARGETHELP)))
< +override CFLAGS += -fexpensive-optimizations -mmmx -msse -msse2 -msse3
< +else
< +override CFLAGS += -fexpensive-optimizations
< +endif
< +
<  # The linker for powerpc have bug that prevents --gc-sections from working
<  # Check for the linker version and if it matches disable --gc-sections
<  # For more information about the bug see:
< @@ -267,6 +274,23 @@
<  SRC-$(CONFIG_MODULE_CCCAM) += module-cccam.c
<  SRC-$(CONFIG_MODULE_CCCSHARE) += module-cccshare.c
<  SRC-$(CONFIG_MODULE_CONSTCW) += module-constcw.c
< +SRC-$(CONFIG_WITH_EMU) += module-emulator.c
< +SRC-$(CONFIG_WITH_EMU) += module-emulator-osemu.c
< +SRC-$(CONFIG_WITH_EMU) += module-emulator-stream.c
< +SRC-$(CONFIG_WITH_EMU) += module-emulator-st20.c
< +SRC-$(CONFIG_WITH_EMU) += module-emulator-dre2overcrypt.c
< +SRC-$(CONFIG_WITH_EMU) += ffdecsa/ffdecsa.c
< +UNAME := $(shell uname -s)
< +ifneq ($(UNAME),Darwin)
< +ifndef ANDROID_NDK
< +ifndef ANDROID_STANDALONE_TOOLCHAIN
< +ifeq "$(CONFIG_WITH_EMU)" "y"
< +TOUCH_SK := $(shell touch SoftCam.Key)
< +override LDFLAGS += -Wl,--format=binary -Wl,SoftCam.Key -Wl,--format=default
< +endif
< +endif
< +endif
< +endif
<  SRC-$(CONFIG_CS_CACHEEX) += module-csp.c
<  SRC-$(CONFIG_CW_CYCLE_CHECK) += module-cw-cycle-check.c
<  SRC-$(CONFIG_WITH_AZBOX) += module-dvbapi-azbox.c
< @@ -359,7 +383,7 @@
<  # starts the compilation.
<  all:
<  	@./config.sh --use-flags "$(USE_FLAGS)" --objdir "$(OBJDIR)" --make-config.mak
< -	@-mkdir -p $(OBJDIR)/cscrypt $(OBJDIR)/csctapi $(OBJDIR)/minilzo $(OBJDIR)/webif
< +	@-mkdir -p $(OBJDIR)/cscrypt $(OBJDIR)/csctapi $(OBJDIR)/minilzo $(OBJDIR)/ffdecsa $(OBJDIR)/webif
<  	@-printf "\
<  +-------------------------------------------------------------------------------\n\
<  | OSCam ver: $(VER) rev: $(SVN_REV) target: $(TARGET)\n\
149c98
< --- config.h	(revision 11212)
---
> --- config.h	(revision 11086)
161c110
< --- config.sh	(revision 11212)
---
> --- config.sh	(revision 11086)
219c168
< --- cscrypt/md5.c	(revision 11212)
---
> --- cscrypt/md5.c	(revision 11086)
264c213
< --- cscrypt/md5.h	(revision 11212)
---
> --- cscrypt/md5.h	(revision 11086)
287c236
< --- csctapi/cardreaders.h	(revision 11212)
---
> --- csctapi/cardreaders.h	(revision 11086)
2964c2913
< --- globals.h	(revision 11212)
---
> --- globals.h	(revision 11086)
3020c2969
< @@ -2141,6 +2151,18 @@
---
> @@ -2141,6 +2151,17 @@
3033d2981
< +	int8_t      emu_stream_emm_enabled;
3039c2987
< @@ -2313,4 +2335,6 @@
---
> @@ -2313,4 +2334,6 @@
3045a2994,3044
> Index: Makefile
> ===================================================================
> --- Makefile	(revision 11086)
> +++ Makefile	(working copy)
> @@ -65,6 +65,13 @@
>  
>  LDFLAGS = -Wl,--gc-sections
>  
> +TARGETHELP := $(shell $(CC) --target-help)
> +ifneq (,$(findstring sse2,$(TARGETHELP)))
> +override CFLAGS += -fexpensive-optimizations -mmmx -msse -msse2 -msse3
> +else
> +override CFLAGS += -fexpensive-optimizations
> +endif
> +
>  # The linker for powerpc have bug that prevents --gc-sections from working
>  # Check for the linker version and if it matches disable --gc-sections
>  # For more information about the bug see:
> @@ -267,6 +274,23 @@
>  SRC-$(CONFIG_MODULE_CCCAM) += module-cccam.c
>  SRC-$(CONFIG_MODULE_CCCSHARE) += module-cccshare.c
>  SRC-$(CONFIG_MODULE_CONSTCW) += module-constcw.c
> +SRC-$(CONFIG_WITH_EMU) += module-emulator.c
> +SRC-$(CONFIG_WITH_EMU) += module-emulator-osemu.c
> +SRC-$(CONFIG_WITH_EMU) += module-emulator-stream.c
> +SRC-$(CONFIG_WITH_EMU) += module-emulator-st20.c
> +SRC-$(CONFIG_WITH_EMU) += module-emulator-dre2overcrypt.c
> +SRC-$(CONFIG_WITH_EMU) += ffdecsa/ffdecsa.c
> +UNAME := $(shell uname -s)
> +ifneq ($(UNAME),Darwin)
> +ifndef ANDROID_NDK
> +ifndef ANDROID_STANDALONE_TOOLCHAIN
> +ifeq "$(CONFIG_WITH_EMU)" "y"
> +TOUCH_SK := $(shell touch SoftCam.Key)
> +override LDFLAGS += -Wl,--format=binary -Wl,SoftCam.Key -Wl,--format=default
> +endif
> +endif
> +endif
> +endif
>  SRC-$(CONFIG_CS_CACHEEX) += module-csp.c
>  SRC-$(CONFIG_CW_CYCLE_CHECK) += module-cw-cycle-check.c
>  SRC-$(CONFIG_WITH_AZBOX) += module-dvbapi-azbox.c
> @@ -359,7 +383,7 @@
>  # starts the compilation.
>  all:
>  	@./config.sh --use-flags "$(USE_FLAGS)" --objdir "$(OBJDIR)" --make-config.mak
> -	@-mkdir -p $(OBJDIR)/cscrypt $(OBJDIR)/csctapi $(OBJDIR)/minilzo $(OBJDIR)/webif
> +	@-mkdir -p $(OBJDIR)/cscrypt $(OBJDIR)/csctapi $(OBJDIR)/minilzo $(OBJDIR)/ffdecsa $(OBJDIR)/webif
>  	@-printf "\
>  +-------------------------------------------------------------------------------\n\
>  | OSCam ver: $(VER) rev: $(SVN_REV) target: $(TARGET)\n\
3048c3047
< --- module-dvbapi.c	(revision 11212)
---
> --- module-dvbapi.c	(revision 11086)
3050c3049
< @@ -1439,7 +1439,15 @@
---
> @@ -1332,7 +1332,15 @@
3067c3066
< @@ -1458,7 +1466,14 @@
---
> @@ -1351,7 +1359,14 @@
3083c3082
< @@ -1559,7 +1574,7 @@
---
> @@ -1454,7 +1469,7 @@
3092c3091
< @@ -3026,7 +3041,7 @@
---
> @@ -2866,7 +2881,7 @@
3101c3100
< @@ -4273,6 +4288,7 @@
---
> @@ -4112,6 +4127,7 @@
3109c3108
< @@ -4299,9 +4315,24 @@
---
> @@ -4138,9 +4154,24 @@
3136,3145c3135
< @@ -5677,7 +5708,7 @@
<  		cs_hexdump(0, demux[demux_id].lastcw[n], 8, lastcw, sizeof(lastcw));
<  		cs_hexdump(0, cw + (n * 8), 8, newcw, sizeof(newcw));
<  
< -		if((memcmp(cw + (n * 8), demux[demux_id].lastcw[n], 8) != 0 || cwEmpty)
< +		if((memcmp(cw + (n * 8), demux[demux_id].lastcw[n], 8) != 0 || cwEmpty || stream_id > 1)
<  				&& memcmp(cw + (n * 8), nullcw, 8) != 0) // check if already delivered and new cw part is valid!
<  		{
<  			ca_index_t idx = dvbapi_ca_setpid(demux_id, pid, stream_id, (algo == CA_ALGO_DES));  // prepare ca
< @@ -6074,6 +6105,7 @@
---
> @@ -5534,6 +5565,7 @@
3153,3162d3142
< @@ -6119,7 +6151,8 @@
<  							cw = er->cw;
<  						}
<  						// Audio
< -						else if(stream_type == 0x03 || stream_type == 0x04 || stream_type == 0x0F || stream_type == 0x11 
< +						else if(stream_type == 0x03 || stream_type == 0x04 || stream_type == 0x06 
< +							|| stream_type == 0x0F || stream_type == 0x11 
<  							|| stream_type == 0x81 || (stream_type >= 0x83 && stream_type <= 0x87) || stream_type == 0x8A)
<  						{
<  							cw = er->cw_ex.audio[key_pos_a];
3165c3145
< --- module-dvbapi.h	(revision 11212)
---
> --- module-dvbapi.h	(revision 11086)
3167,3168c3147,3148
< @@ -135,6 +135,7 @@
<  	ca_index_t index[MAX_STREAM_INDICES];
---
> @@ -108,6 +108,7 @@
>  	int8_t index[MAX_STREAM_INDICES];
3833c3813
< @@ -0,0 +1,4291 @@
---
> @@ -0,0 +1,4225 @@
4010c3990
< +		snprintf(line, sizeof(line), "\n%c %08X %s %s ; added by OSEmu %s %s\n", identifier, provider, keyName, keyValue, dateText, comment);
---
> +		snprintf(line, sizeof(line), "\n%c %04X %s %s ; added by OSEmu %s %s\n", identifier, provider, keyName, keyValue, dateText, comment);
4016d3995
< +	cs_log("[Emu] Key written: %c %08X %s %s", identifier, provider, keyName, keyValue);
4032d4010
< +	uint8_t key_exists = 0;
4067c4045
< +		if(strcmp(KeyDB->EmuKeys[i].keyName, keyName)) {
---
> +		if(KeyDB->EmuKeys[i].provider != provider) {
4070,4092c4048,4049
< +
< +		if( identifier == 'P' ) {
< +			if(writeKey) {
< +				if( (KeyDB->EmuKeys[i].provider & 0xFFFF0000)  != (provider & 0xFFFF0000) ) { // mask out srvid, only compare group
< +					continue;
< +				}
< +				tmpKeyData = &KeyDB->EmuKeys[i];
< +				if(memcmp(tmpKeyData->key, key, tmpKeyData->keyLength < keyLength ? tmpKeyData->keyLength : keyLength) == 0) {
< +					key_exists = 1;
< +					continue;
< +				}
< +				provider = KeyDB->EmuKeys[i].provider; // set to matched full provider ( group + srvid )
< +			}
< +			else {
< +				if( KeyDB->EmuKeys[i].provider != provider ) { 
< +                                        continue;
< +                                }
< +			}
< +		}
< +		else {
< +			if(KeyDB->EmuKeys[i].provider != provider) {
< +				continue;
< +			}
---
> +		if(strcmp(KeyDB->EmuKeys[i].keyName, keyName)) {
> +			continue;
4094d4050
< +		key_exists = 1;
4097c4053
< +		if(identifier == 'I')
---
> +		if(identifier == 'I' || identifier == 'P')
4154c4110
< +		else // identifier != 'I' 
---
> +		else // identifier != ('I' || 'P')
4168,4173d4123
< +		if((identifier != 'P') | !writeKey){ // on pvu update continue loop to find others in group
< +			return 1;
< +		}
< +	}
< +
< +	if(key_exists) {
4230d4179
< +	uint8_t k;
4239d4187
< +	k = 0;
4241,4250c4189,4190
< +		if(identifier == 'P') {
< +			if( getProvider == NULL && (KeyDB->EmuKeys[i].provider & 0x0000FFFF)  != provider ) { // mask out group, only compare srvid
< +				continue;
< +			}
< +			//provider = KeyDB->EmuKeys[i].provider; // set to matched full provider ( group + srvid )
< +		}
< +		else {
< +			if(getProvider == NULL && KeyDB->EmuKeys[i].provider != provider) {
< +				continue;
< +			}
---
> +		if(getProvider == NULL && KeyDB->EmuKeys[i].provider != provider) {
> +			continue;
4252d4191
< +
4264,4273d4202
< +		if(identifier == 'P') {
< +			if(k < keyRef) {
< +				k++;
< +				continue;
< +			}
< +			else {
< +				keyRef = 0;
< +			}
< +		}
< +
7820c7749
< +		cs_log_dbg(D_EMM,"[Emu] EMM error: AU key for UA %s is missing", keyName);
---
> +		cs_log("[Emu] EMM eror: AU key for UA %s is missing", keyName);
7870c7799
< +		if(!SetKey('P', channelId<<16, keyName, newEcmKey, 7, 1, uaInfo)) {
---
> +		if(!UpdateKey('P', channelId, keyName, newEcmKey, 7, uaInfo)) {
7883,7884c7812
< +	uint32_t i,j;
< +	uint32_t groupid;
---
> +	uint32_t i;
7896c7824
< +		if(srvid != 0xFFFF && (KeyDB->EmuKeys[i].provider & 0x0000FFFF) != srvid)
---
> +		if(srvid != 0xFFFF && KeyDB->EmuKeys[i].provider != srvid)
7899,7915c7827
< +		groupid = KeyDB->EmuKeys[i].provider>>16;
< +
< +		for(j=0; j<KeyDB->keyCount && (*count)<length ; j++) {
< +
< +			if(srvid != 0xFFFF && KeyDB->EmuKeys[j].provider != groupid)
< +				{ continue; }
< +			
< +			len = strlen(KeyDB->EmuKeys[j].keyName);
< +			
< +			if(len < 3)
< +				{ continue;}
< +			
< +			if(len > 8)
< +				{ len = 8; }
< +
< +			memset(hexserials[*count], 0, 4);
< +			CharToBin(hexserials[(*count)]+(4-(len/2)), KeyDB->EmuKeys[j].keyName, len);
---
> +		len = strlen(KeyDB->EmuKeys[i].keyName);
7917,7921c7829,7838
< +			(*count)++;
< +		}
< +		if(srvid == 0xFFFF) {
< +			return ((*count)>0);
< +		}
---
> +		if(len < 3)
> +			{ continue;}
> +		
> +		if(len > 8)
> +			{ len = 8; }
> +
> +		memset(hexserials[*count], 0, 4);
> +		CharToBin(hexserials[(*count)]+(4-(len/2)), KeyDB->EmuKeys[i].keyName, len);
> +	
> +		(*count)++;
8111,8113d8027
< +		if(result == 2) { // missing key already logged
< +			return 2;
< +		}
8120c8034
< +		cs_log_dbg(D_EMM,"[Emu] EMM failed: %s", GetProcessEMMErrorReason(result));
---
> +		cs_log("[Emu] EMM failed: %s", GetProcessEMMErrorReason(result));
8657c8571
< @@ -0,0 +1,1084 @@
---
> @@ -0,0 +1,1036 @@
8685d8598
< +int8_t emu_stream_emm_enabled = 0;
8842c8755
< +			cs_log_dbg(D_READER, "[Emu] stream %i found pmt  pid : 0x%04X (%i)",cdata->connid, cdata->pmt_pid, cdata->pmt_pid);
---
> +			cs_log_dbg(D_READER, "[Emu] stream found pmt pid: %X", cdata->pmt_pid);
8882c8795
< +		    	cs_log_dbg(D_READER, "[Emu] stream %i found ecm  pid : 0x%04X (%i)",cdata->connid, cdata->ecm_pid, cdata->ecm_pid);
---
> +		    	cs_log_dbg(D_READER, "[Emu] stream found ecm_pid: %X", cdata->ecm_pid);
8899c8812
< +			cs_log_dbg(D_READER, "[Emu] stream %i found video pid: 0x%04X (%i)",cdata->connid, stream_pid, stream_pid);
---
> +			cs_log_dbg(D_READER, "[Emu] stream found video pid: %X", stream_pid);
8902,8903c8815,8816
< +		else if(stream_type == 0x03 || stream_type == 0x04 || stream_type == 0x05 || stream_type == 0x06 ||
< +				stream_type == 0x0F || stream_type == 0x11 || stream_type == 0x81 || stream_type == 0x87)
---
> +		else if(stream_type == 0x03 || stream_type == 0x04 || stream_type == 0x0F || stream_type == 0x11 
> +			|| stream_type == 0x81 || stream_type == 0x87)
8910c8823
< +			cs_log_dbg(D_READER, "[Emu] stream %i found audio pid: 0x%04X (%i)", cdata->connid, stream_pid, stream_pid);
---
> +			cs_log_dbg(D_READER, "[Emu] stream found audio pid: %X", stream_pid);
8936,8938c8849,8851
< +//#ifdef WITH_EMU
< +//static void ParseTSPackets(emu_stream_client_conn_data *conndata, emu_stream_client_data *data, uint8_t *stream_buf, uint32_t bufLength, uint16_t packetSize)
< +//#else
---
> +#ifdef WITH_EMU
> +static void ParseTSPackets(emu_stream_client_conn_data *conndata, emu_stream_client_data *data, uint8_t *stream_buf, uint32_t bufLength, uint16_t packetSize)
> +#else
8940c8853
< +//#endif
---
> +#endif
8960,8961d8872
< +	uint32_t keysAdded = 0;
< +	uint8_t *cptr;
8978,9007d8888
< +		if( pid == 0x01 && emu_stream_emm_enabled && !data->emm_pid ) // CAT 
< +		{
< +			cptr = stream_buf+i+offset;
< +			j = 0;
< +			while (cptr != NULL)
< +			{
< +				cptr = memchr (stream_buf+i+offset+j, 0x0E,100);
< +				if (cptr != NULL)
< +			 	{
< +					if (*(cptr+1) == 00) 
< +					{
< +						data->emm_pid = (b2i(2,cptr+2) & 0x1FFF);
< +		    				cs_log_dbg(D_READER|D_EMM, "[Emu] stream %i found emm  pid : 0x%04X (%i)",data->connid, data->emm_pid, data->emm_pid);
< +						break;
< +					}
< +				j = cptr - stream_buf +i + 1;
< +				}
< +			}
< +		}
< +	
< +		if(pid == data->emm_pid && data->emm_pid)
< +		{
< +			ProcessEMM(0x0E00,0x0,stream_buf+i+offset+1, &keysAdded);	
< +			if(keysAdded) 
< +			{
< +				cs_log("[Emu] stream %i found %i keys.",data->connid, keysAdded);
< +			}
< +
< +		}
< +
9039c8920
< +			stream_server_has_ecm[data->connid] = 1;
---
> +			stream_server_has_ecm[conndata->connid] = 1;
9046c8927
< +	
---
> +		
9059c8940
< +		if(!stream_server_has_ecm[data->connid])
---
> +		if(!stream_server_has_ecm[conndata->connid])
9061,9062c8942,8943
< +			keydata = &emu_fixed_key_data[data->connid];
< +			SAFE_MUTEX_LOCK(&emu_fixed_key_data_mutex[data->connid]);
---
> +			keydata = &emu_fixed_key_data[conndata->connid];
> +			SAFE_MUTEX_LOCK(&emu_fixed_key_data_mutex[conndata->connid]);
9207c9088
< +		if(!stream_server_has_ecm[data->connid])
---
> +		if(!stream_server_has_ecm[conndata->connid])
9209c9090
< +			SAFE_MUTEX_UNLOCK(&emu_fixed_key_data_mutex[data->connid]); 
---
> +			SAFE_MUTEX_UNLOCK(&emu_fixed_key_data_mutex[conndata->connid]); 
9229c9110
< +		cs_log("[Emu] error: setsockopt() failed for SO_RCVTIMEO"); 
---
> +		cs_log("setsockopt() failed for SO_RCVTIMEO"); 
9290,9291d9170
< +	cs_log("[Emu] stream client %i disconnected",conndata->connid);
< +	
9292a9172,9173
> +	
> +	cs_log("[Emu] stream client disconnected");
9320,9321c9201,9202
< +
< +	cs_log("[Emu] stream client %i connected", conndata->connid);
---
> +	
> +	cs_log("[Emu] stream client connected");
9402c9283
< +	cs_log("[Emu] stream client %i request %s", conndata->connid, stream_path);
---
> +	cs_log("[Emu] stream client request %s", stream_path);
9407,9408d9287
< +	data->connid = conndata->connid;
< +
9414c9293
< +			cs_log("[Emu] warning: stream client %i cannot connect to stream source", conndata->connid);
---
> +			cs_log("[Emu] warning: cannot connect to stream source");
9437c9316
< +			if(streamStatus == 0) // socket closed
---
> +			if(streamStatus == -1)
9439,9441c9318
< +				cs_log("[Emu] warning: stream client %i - stream source closed connection", conndata->connid);
< +				streamConnectErrorCount++;
< +				cs_sleepms(100);
---
> +				streamDataErrorCount++;
9445c9322
< +			if(streamStatus < 0) // error
---
> +			if(streamStatus == 0)
9447,9454c9324,9325
< +				if ((errno == EWOULDBLOCK) | (errno == EAGAIN)) {
< +					cs_log("[Emu] warning: stream client %i no data from stream source", conndata->connid);
< +					streamDataErrorCount++; // 2 sec timeout * 15 = 30 seconds no data -> close
< +					cs_sleepms(100);
< +					continue;
< +				}
< +				cs_log("[Emu] warning: stream client %i error receiving data from stream source", conndata->connid);
< +				streamConnectErrorCount++;
---
> +				cs_log("[Emu] warning: no data from stream source");
> +				streamDataErrorCount++; // 2 sec timeout * 15 = 30 seconds no data -> close
9456c9327
< +				break;
---
> +				continue;	
9458c9329
< +
---
> +			
9465c9336
< +					cs_log("[Emu] error: stream client %i got %d response from stream source", conndata->connid, http_status_code);
---
> +					cs_log("[Emu] error: got %d response from stream source", http_status_code);
9472,9474c9343
< +					cs_log_dbg(0, "[Emu] warning: stream client %i non-full buffer from stream source", conndata->connid);
< +					streamDataErrorCount++;
< +					cs_sleepms(100);
---
> +					cs_log_dbg(0, "[Emu] warning: non-full buffer from stream source");
9477,9480d9345
< +			else
< +			{
< +				streamDataErrorCount = 0;
< +			}
9482a9348
> +			streamDataErrorCount = 0;
9500,9502c9366,9368
< +//#ifdef WITH_EMU
< +//					ParseTSPackets(conndata, data, stream_buf+startOffset, packetCount*packetSize, packetSize);
< +//#else
---
> +#ifdef WITH_EMU
> +					ParseTSPackets(conndata, data, stream_buf+startOffset, packetCount*packetSize, packetSize);
> +#else
9504c9370
< +//#endif					
---
> +#endif					
9636c9502
< +				cs_log("[Emu] error: stream client %i setsockopt() failed for TCP_NODELAY", conndata->connid); 
---
> +				cs_log("setsockopt() failed for TCP_NODELAY"); 
9645c9511
< +			cs_log("[Emu] error: stream server client dropped because of too many connections (%i)", EMU_STREAM_SERVER_MAX_CONNECTIONS);
---
> +			cs_log("[Emu] error: stream server client dropped because of too much connections");
9746c9612
< @@ -0,0 +1,64 @@
---
> @@ -0,0 +1,61 @@
9762d9627
< +		int32_t connid;
9771d9635
< +		uint16_t emm_pid;
9783d9646
< +	extern int8_t emu_stream_emm_enabled;
9815c9678
< @@ -0,0 +1,715 @@
---
> @@ -0,0 +1,714 @@
10397d10259
< +		emu_stream_emm_enabled = cfg.emu_stream_emm_enabled;
10496c10358
< +						"1801:000000,007301,001101;"
---
> +						"1801:000000,007301,001101,002111;"
10533c10395
< --- module-newcamd-des.c	(revision 11212)
---
> --- module-newcamd-des.c	(revision 11086)
10557c10419
< --- module-newcamd-des.h	(revision 11212)
---
> --- module-newcamd-des.h	(revision 11086)
10577c10439
< --- module-stat.c	(revision 11212)
---
> --- module-stat.c	(revision 11086)
10599c10461
< --- module-webif-tpl.c	(revision 11212)
---
> --- module-webif-tpl.c	(revision 11086)
10611c10473
< --- module-webif.c	(revision 11212)
---
> --- module-webif.c	(revision 11086)
10613c10475
< @@ -98,6 +98,7 @@
---
> @@ -103,6 +103,7 @@
10621c10483
< @@ -119,8 +120,9 @@
---
> @@ -124,8 +125,9 @@
10632c10494
< @@ -942,6 +944,34 @@
---
> @@ -947,6 +949,31 @@
10657,10659d10518
< +	tpl_printf(vars, TPLADD, "TMP", "STREAMEMMENABLEDSELECTED%d", cfg.emu_stream_emm_enabled);
< +	tpl_addVar(vars, TPLADD, tpl_getVar(vars, "TMP"), "selected");
< +
10667c10526
< @@ -1355,6 +1385,9 @@
---
> @@ -1360,6 +1387,9 @@
10677c10536
< @@ -1793,7 +1826,7 @@
---
> @@ -1798,7 +1828,7 @@
10686c10545
< @@ -2350,6 +2383,13 @@
---
> @@ -2355,6 +2385,13 @@
10700c10559
< @@ -2370,6 +2410,9 @@
---
> @@ -2375,6 +2412,9 @@
10710c10569
< @@ -4047,9 +4090,38 @@
---
> @@ -4052,9 +4092,38 @@
10749c10608
< @@ -4516,6 +4588,9 @@
---
> @@ -4542,6 +4611,9 @@
10759c10618
< @@ -5923,6 +5998,9 @@
---
> @@ -5972,6 +6044,9 @@
10769c10628
< @@ -6388,7 +6466,7 @@
---
> @@ -6437,7 +6512,7 @@
10778c10637
< @@ -7393,8 +7471,8 @@
---
> @@ -7442,8 +7517,8 @@
10791c10650
< --- oscam-chk.c	(revision 11212)
---
> --- oscam-chk.c	(revision 11086)
10811c10670
< @@ -977,7 +977,7 @@
---
> @@ -975,7 +975,7 @@
10822c10681
< --- oscam-config-global.c	(revision 11212)
---
> --- oscam-config-global.c	(revision 11086)
10824c10683
< @@ -803,6 +803,30 @@
---
> @@ -803,6 +803,29 @@
10843,10844c10702
< +	DEF_OPT_UINT8("stream_relay_enabled"     , OFS(emu_stream_relay_enabled),        1),
< +	DEF_OPT_UINT8("stream_emm_enabled"       , OFS(emu_stream_emm_enabled),          0),
---
> +	DEF_OPT_UINT32("stream_relay_enabled"     , OFS(emu_stream_relay_enabled),        1),
10855c10713
< @@ -1008,7 +1032,7 @@
---
> @@ -1008,7 +1031,7 @@
10864c10722
< @@ -1062,6 +1086,7 @@
---
> @@ -1062,6 +1085,7 @@
10874c10732
< --- oscam-config-reader.c	(revision 11212)
---
> --- oscam-config-reader.c	(revision 11086)
10913c10771
< --- oscam-config.h	(revision 11212)
---
> --- oscam-config.h	(revision 11086)
10935c10793
< --- oscam-ecm.c	(revision 11212)
---
> --- oscam-ecm.c	(revision 11086)
10948c10806
< --- oscam-emm.c	(revision 11212)
---
> --- oscam-emm.c	(revision 11086)
10993c10851
< --- oscam-string.c	(revision 11212)
---
> --- oscam-string.c	(revision 11086)
11060c10918
< --- oscam-string.h	(revision 11212)
---
> --- oscam-string.h	(revision 11086)
11072c10930
< --- oscam.c	(revision 11212)
---
> --- oscam.c	(revision 11086)
11094c10952
< @@ -1588,6 +1594,9 @@
---
> @@ -1584,6 +1590,9 @@
11104c10962
< @@ -1759,6 +1768,9 @@
---
> @@ -1755,6 +1764,9 @@
11114c10972
< @@ -1842,6 +1854,9 @@
---
> @@ -1838,6 +1850,9 @@
11126c10984
< --- reader-common.c	(revision 11212)
---
> --- reader-common.c	(revision 11086)
11158c11016
< --- reader-dre.c	(revision 11212)
---
> --- reader-dre.c	(revision 11086)
11373c11231
< --- readers.h	(revision 11212)
---
> --- readers.h	(revision 11086)
11384c11242
< --- webif/config/dvbapi.html	(revision 11212)
---
> --- webif/config/dvbapi.html	(revision 11086)
11405c11263
< --- webif/config/menu.html	(revision 11212)
---
> --- webif/config/menu.html	(revision 11086)
11426c11284
< @@ -0,0 +1,26 @@
---
> @@ -0,0 +1,18 @@
11438,11445d11295
< +			<TR><TD><A>Process EMM from stream </A></TD>
< +				<TD>
< +					<select name="stream_emm_enabled">
< +						<option value="0" ##STREAMEMMENABLEDSELECTED0##>0 - disabled </option>
< +						<option value="1" ##STREAMEMMENABLEDSELECTED1##>1 - enabled </option>
< +					</select>
< +				</TD>
< +			</TR>
11452a11303
> \ No newline at end of file
11455c11306
< --- webif/files/menu.html	(revision 11212)
---
> --- webif/files/menu.html	(revision 11086)
11482c11333
< --- webif/pages_index.txt	(revision 11212)
---
> --- webif/pages_index.txt	(revision 11086)
11506c11357
< @@ -181,6 +184,7 @@
---
> @@ -180,6 +183,7 @@
